[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "hyperopt",
    "numpy",
    "pandas",
    "scikit-learn",
    "sklearn",
    "statsmodels",
]
build-backend = "setuptools.build_meta"